---
# For complete sample of all build and test jobs,
# see <gecko>/testing/taskcluster/tasks/job_flags.yml

$inherits:
  from: tasks/branches/base_job_flags.yml

builds:
  linux64-mulet:
    platforms:
      - Mulet Linux
    types:
      opt:
        task: tasks/builds/mulet_linux.yml
  emulator-kk:
    platfoms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_emulator_kk_opt.yml
      debug:
        task: tasks/builds/b2g_emulator_kk_debug.yml
  emulator-x86-kk:
    platfoms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_emulator_x86_kk_opt.yml
      debug:
        task: tasks/builds/b2g_emulator_x86_kk_debug.yml
  emulator-l:
    platfoms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_emulator_l_opt.yml
      debug:
        task: tasks/builds/b2g_emulator_l_debug.yml
  linux:
    platfoms:
      - Linux
    types:
      opt:
        task: tasks/builds/opt_linux32.yml
      debug:
        task: tasks/builds/dbg_linux32.yml
  aries:
    platforms:
<<<<<<< HEAD
      - b2g
=======
      - Linux64
    extra-builds:  # see RIDEALONG_BUILDS in `mach taskgraph`
      - sm-plain
      - sm-nonunified
      - sm-arm-sim
      - sm-compacting
      - sm-rootanalysis
      - sm-package
>>>>>>> 275003c073 (Bug 1273917 - Create the SM(pkg) build for taskcluster; r=sfink)
    types:
      opt:
        task: tasks/builds/b2g_aries_spark_opt.yml
      debug:
        task: tasks/builds/b2g_aries_spark_debug.yml
  aries-eng:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_aries_spark_eng.yml
  flame-kk:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_flame_kk_opt.yml
      debug:
        task: tasks/builds/b2g_flame_kk_debug.yml
  flame-kk-eng:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/opt_linux64_pgo.yml
  macosx64:
    platforms:
      - MacOSX64
    types:
      opt:
        task: tasks/builds/opt_macosx64.yml
      debug:
        task: tasks/builds/dbg_macosx64.yml
  macosx64-st-an:
    platforms:
      - MacOSX64 Static Analysis
    types:
      opt:
        task: tasks/builds/opt_macosx64_st-an.yml
  linux64-mulet-haz:
    platforms:
      - Mulet Linux
    types:
      debug:
        task: tasks/builds/mulet_haz_linux.yml
  sm-plain:
    platforms:
      - Linux64
    types:
      opt:
        task: tasks/builds/sm_plain.yml
      debug:
        task: tasks/builds/sm_plaindebug.yml
    when:
      file_patterns:
       - js/public/**
       - js/src/**
  sm-nonunified:
    platforms:
      - Linux64
    types:
      debug:
        task: tasks/builds/sm_nonunified.yml
    when:
      file_patterns:
       - js/public/**
       - js/src/**
  sm-arm-sim:
    platforms:
      - Linux64
    types:
      debug:
        task: tasks/builds/sm_arm_sim.yml
    when:
      file_patterns:
       - js/public/**
       - js/src/**
  sm-arm64-sim:
    platforms:
      - Linux64
    types:
      debug:
        task: tasks/builds/sm_arm64_sim.yml
    when:
      file_patterns:
       - js/public/**
       - js/src/**
  sm-arm64-sim:
    platforms:
      - Linux64
    types:
      debug:
        task: tasks/builds/sm_arm64_sim.yml
    when:
      file_patterns:
       - js/public/**
       - js/src/**
  sm-arm-sim-osx:
    platforms:
      - Linux64
    types:
      debug:
        task: tasks/builds/sm_arm_sim_osx.yml
    when:
      file_patterns:
       - js/public/**
       - js/src/**
  sm-compacting:
    platforms:
      - Linux64
    types:
      debug:
        task: tasks/builds/sm_compacting.yml
    when:
      file_patterns:
       - js/public/**
       - js/src/**
  sm-package:
    platforms:
      - Linux64
    types:
      opt:
        task: tasks/builds/sm_package.yml
    when:
      # Make sure this list stays in sync with the files and directories copied
      # by `js/src/make-source-package.sh`!
      file_patterns:
        - build/**
        - configure.py
        - dom/bindings/**
        - intl/icu/**
        - js/moz.configure
        - js/public/**
        - js/src/**
        - layout/tools/reftest/reftest/**
        - media/webrtc/trunk/tools/gyp/**
        - memory/**
        - mfbt/**
        - modules/fdlibm/**
        - modules/zlib/src/**
        - mozglue/**
        - moz.configure
        - nsprpub/**
        - python/**
        - taskcluster/moz.build
        - testing/mozbase/**
        - test.mozbuild
        - toolkit/mozapps/installer/package-name.mk
        - toolkit/mozapps/installer/upload-files.mk
  sm-rootanalysis:
    platforms:
      - Linux64
    types:
      debug:
        task: tasks/builds/sm_rootanalysis.yml
    when:
      file_patterns:
       - js/public/**
       - js/src/**

tests:
  cppunit:
    allowed_build_tasks:
      tasks/builds/b2g_emulator_ics_opt.yml:
        task: tasks/tests/b2g_emulator_cpp_unit.yml
      tasks/builds/b2g_emulator_ics_debug.yml:
        task: tasks/tests/b2g_emulator_cpp_unit.yml
  crashtest:
    allowed_build_tasks:
      tasks/builds/b2g_emulator_ics_opt.yml:
        task: tasks/tests/b2g_emulator_crashtest.yml
  gaia-build:
    allowed_build_tasks:
      tasks/builds/b2g_desktop_opt.yml:
        task: tasks/tests/b2g_build_test.yml
  gaia-build-unit:
    allowed_build_tasks:
      tasks/builds/b2g_desktop_opt.yml:
        task: tasks/tests/b2g_build_unit.yml
  gaia-js-integration:
    allowed_build_tasks:
      tasks/builds/b2g_desktop_opt.yml:
        task: tasks/tests/b2g_gaia_js_integration_tests.yml
  gaia-linter:
    allowed_build_tasks:
      tasks/builds/b2g_desktop_opt.yml:
        task: tasks/tests/b2g_linter.yml
  gaia-ui-test-accessibility:
    allowed_build_tasks:
      tasks/builds/b2g_desktop_opt.yml:
        task: tasks/tests/b2g_gaia_ui_test_accessibility.yml
      tasks/builds/b2g_desktop_debug.yml:
        task: tasks/tests/b2g_gaia_ui_test_accessibility.yml
  gaia-ui-test-functional:
    allowed_build_tasks:
      tasks/builds/b2g_desktop_opt.yml:
        task: tasks/tests/b2g_gaia_ui_test_functional.yml
      tasks/builds/b2g_desktop_debug.yml:
        task: tasks/tests/b2g_gaia_ui_test_functional.yml
      tasks/builds/b2g_flame_kk_eng.yml:
        task: tasks/tests/flame_kk_gaia_ui_test_functional.yml
  gaia-ui-test-functional-dsds:
    allowed_build_tasks:
      tasks/builds/b2g_flame_kk_eng.yml:
        task: tasks/tests/flame_kk_gaia_ui_test_functional_dsds.yml
  gaia-ui-test-sanity:
    allowed_build_tasks:
      tasks/builds/b2g_flame_kk_eng.yml:
        task: tasks/tests/flame_kk_gaia_ui_test_sanity.yml
  gaia-ui-test-unit:
    allowed_build_tasks:
      tasks/builds/b2g_desktop_opt.yml:
        task: tasks/tests/b2g_gaia_ui_test_unit.yml
      tasks/builds/b2g_desktop_debug.yml:
        task: tasks/tests/b2g_gaia_ui_test_unit.yml
      tasks/builds/b2g_flame_kk_eng.yml:
        task: tasks/tests/flame_kk_gaia_ui_test_unit.yml
  gaia-unit:
    allowed_build_tasks:
      tasks/builds/b2g_desktop_opt.yml:
        task: tasks/tests/b2g_gaia_unit.yml
  marionette:
    allowed_build_tasks:
      tasks/builds/b2g_emulator_ics_opt.yml:
        task: tasks/tests/b2g_emulator_marionette.yml
  marionette-webapi:
    allowed_build_tasks:
      tasks/builds/b2g_emulator_ics_opt.yml:
        task: tasks/tests/b2g_emulator_marionette_webapi.yml
  mochitest:
    allowed_build_tasks:
      tasks/builds/b2g_emulator_ics_opt.yml:
        task: tasks/tests/b2g_emulator_mochitest.yml
      tasks/builds/b2g_emulator_ics_debug.yml:
        task: tasks/tests/b2g_emulator_mochitest.yml
      tasks/builds/mulet_linux.yml:
        task: tasks/tests/mulet_mochitests.yml
  mochitest-oop:
    allowed_build_tasks:
      tasks/builds/b2g_desktop_opt.yml:
        task: tasks/tests/b2g_mochitest_oop.yml
  reftest:
    allowed_build_tasks:
      tasks/builds/mulet_linux.yml:
        task: tasks/tests/mulet_reftests.yml
      tasks/builds/b2g_emulator_ics_opt.yml:
        task: tasks/tests/b2g_emulator_reftest.yml
  reftest-sanity-oop:
    allowed_build_tasks:
      tasks/builds/b2g_desktop_opt.yml:
        task: tasks/tests/b2g_reftests_sanity_oop.yml
  xpcshell:
    allowed_build_tasks:
      tasks/builds/b2g_emulator_ics_opt.yml:
        task: tasks/tests/b2g_emulator_xpcshell_chunked.yml
      tasks/builds/b2g_emulator_ics_debug.yml:
        task: tasks/tests/b2g_emulator_xpcshell_chunked.yml
